/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ICaretRight: typeof import('~icons/ph/caret-right')['default']
    ICompass: typeof import('~icons/ph/compass')['default']
    IDotsThreeVertical: typeof import('~icons/ph/dots-three-vertical')['default']
    IFile: typeof import('~icons/ph/file')['default']
    IFolder: typeof import('~icons/ph/folder')['default']
    IFolders: typeof import('~icons/ph/folders')['default']
    IFunnel: typeof import('~icons/ph/funnel')['default']
    IGear: typeof import('~icons/ph/gear')['default']
    ILinkSimple: typeof import('~icons/ph/link-simple')['default']
    IMinus: typeof import('~icons/ph/minus')['default']
    IPlus: typeof import('~icons/ph/plus')['default']
    IQuestion: typeof import('~icons/ph/question')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
